<?php namespace ProcessWire;

class DkCore extends WireData implements Module,ConfigurableModule {

	static protected $defaults = [];

	public static function getModuleInfo() {
		return array(
			'title' => 'DkCore', 
			'version' => 1, 
			'summary' => 'DK - Core Module (loads other modules)',
			'configurable' => true,
			'href' => '',
			'singular' => true, 
			'autoload' => true,
			'icon' => 'kiwi-bird', 
			'installs' => array("InputfieldDKEditor",'DkTemplateEditor',"DkTemplate",'DkForms','DkNavbar','DkConfig'),
        );
	}
	
	public function __construct() {
		$this->setArray(self::$defaults);
	}

	public function ___install(){
		// Create Parent Page
		$newPageGroup = new Page;
		$newPageGroup->parent = $this->pages->get(2);
		$newPageGroup->template = 'admin';
		$newPageGroup->title = 'DK';
		$newPageGroup->name = 'dk';
		$newPageGroup->process = 'ProcessList';
		$newPageGroup->save();
	}

	public function ___uninstall() {
        $this->pages->get($this->config->urls->admin.'dk/')->delete(true);
	}

	public function init() {
	}

	public static function getModuleConfigInputfields(){
		return new InputfieldWrapper;
	}


}
